# Generated by Django 5.2.12 on 2026-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_firmware_upgrader", "0004_alter_firmwareimage_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="persistent",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, devices that are offline at upgrade time will be retried automatically using exponential back-off until the admin cancels the batch or every device succeeds. This flag is immutable once the batch has been created.",
                verbose_name="persistent",
            ),
        ),
        migrations.AddField(
            model_name="batchupgradeoperation",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="UTC datetime at which this batch should start executing. Leave blank for immediate execution.",
                null=True,
                verbose_name="scheduled at",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="next_retry_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Scheduled datetime for the next retry attempt (UTC).",
                null=True,
                verbose_name="next retry at",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this operation has been retried because the device was offline.",
                verbose_name="retry count",
            ),
        ),
        migrations.AddField(
            model_name="upgradeoperation",
            name="waiting_for_device",
            field=models.BooleanField(
                default=False,
                help_text="True when this operation is paused waiting for the device to come back online before the next retry attempt.",
                verbose_name="waiting for device",
            ),
        ),
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("scheduled", "scheduled"),
                    ("in-progress", "in progress"),
                    ("success", "completed successfully"),
                    ("failed", "completed with some failures"),
                    ("cancelled", "completed with some cancellations"),
                ],
                default="idle",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="upgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("in-progress", "in progress"),
                    ("waiting", "waiting for device"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("aborted", "aborted"),
                ],
                default="in-progress",
                max_length=12,
            ),
        ),
    ]
